configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperspell/hyperspell-77ec108abc2bb8bf6df7ce5e574bcb3c96f96a5f5bc0f4ce6ba856523fec591c.yml
openapi_spec_hash: d0d66b814ebe56ac7c0135f9f3aab616
config_hash: e94cd277a0f8a93fc9dbadfd0a99ffcb
