configured_endpoints: 30
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperspell%2Fhyperspell-0b9bf804b7e67e6743eae14b04310e7efddb54d67f7d9c02e11acccd83169255.yml
openapi_spec_hash: 0feb465dcd08ad061bf0a0ce10c9df9f
config_hash: 597eba5e5eaec83a5f0db3d946af8db5
